cryptocompare:
  url: https://min-api.cryptocompare.com/data/pricemulti
  key: 9d58fc75d1c92af7eae04ea63a60d36df49da09d6ac3818daa2e45dbe7e4426a

coinapi:
  url: https://rest.coinapi.io/v1/assets
  key: 73034021-THIS-IS-SAMPLE-KEY
